package Base_donnee;
// Generated 9 mars 2022, 15:00:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "cycle", catalog = "systemdeparrainage")
public class Cycle implements java.io.Serializable {

	private Integer idCycle;
	private String nom;
	private Set<Niveau> niveaus = new HashSet<Niveau>(0);

	public Cycle() {
	}

	public Cycle(String nom) {
		this.nom = nom;
	}

	public Cycle(String nom, Set<Niveau> niveaus) {
		this.nom = nom;
		this.niveaus = niveaus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdCycle", unique = true, nullable = false)
	public Integer getIdCycle() {
		return this.idCycle;
	}

	public void setIdCycle(Integer idCycle) {
		this.idCycle = idCycle;
	}

	@Column(name = "Nom", nullable = false, length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cycle")
	public Set<Niveau> getNiveaus() {
		return this.niveaus;
	}

	public void setNiveaus(Set<Niveau> niveaus) {
		this.niveaus = niveaus;
	}

}
