package Base_donnee;
// Generated 9 mars 2022, 15:00:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", catalog = "systemdeparrainage")
public class Niveau implements java.io.Serializable {

	private Integer idNiveau;
	private Cycle cycle;
	private Filiere filiere;
	private int numero;
	private Set<Parcourt> parcourts = new HashSet<Parcourt>(0);

	public Niveau() {
	}

	public Niveau(Cycle cycle, Filiere filiere, int numero) {
		this.cycle = cycle;
		this.filiere = filiere;
		this.numero = numero;
	}

	public Niveau(Cycle cycle, Filiere filiere, int numero, Set<Parcourt> parcourts) {
		this.cycle = cycle;
		this.filiere = filiere;
		this.numero = numero;
		this.parcourts = parcourts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdNiveau", unique = true, nullable = false)
	public Integer getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(Integer idNiveau) {
		this.idNiveau = idNiveau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCycle", nullable = false)
	public Cycle getCycle() {
		return this.cycle;
	}

	public void setCycle(Cycle cycle) {
		this.cycle = cycle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiliere", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@Column(name = "Numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "niveau")
	public Set<Parcourt> getParcourts() {
		return this.parcourts;
	}

	public void setParcourts(Set<Parcourt> parcourts) {
		this.parcourts = parcourts;
	}

}
