package Base_donnee;
// Generated 9 mars 2022, 15:00:04 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParcourtId generated by hbm2java
 */
@Embeddable
public class ParcourtId implements java.io.Serializable {

	private int idEtudiant;
	private int idNiveau;

	public ParcourtId() {
	}

	public ParcourtId(int idEtudiant, int idNiveau) {
		this.idEtudiant = idEtudiant;
		this.idNiveau = idNiveau;
	}

	@Column(name = "IdEtudiant", nullable = false)
	public int getIdEtudiant() {
		return this.idEtudiant;
	}

	public void setIdEtudiant(int idEtudiant) {
		this.idEtudiant = idEtudiant;
	}

	@Column(name = "IdNiveau", nullable = false)
	public int getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(int idNiveau) {
		this.idNiveau = idNiveau;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParcourtId))
			return false;
		ParcourtId castOther = (ParcourtId) other;

		return (this.getIdEtudiant() == castOther.getIdEtudiant()) && (this.getIdNiveau() == castOther.getIdNiveau());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEtudiant();
		result = 37 * result + this.getIdNiveau();
		return result;
	}

}
