package Base_donnee;
// Generated 9 mars 2022, 15:00:04 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parcourt generated by hbm2java
 */
@Entity
@Table(name = "parcourt", catalog = "systemdeparrainage")
public class Parcourt implements java.io.Serializable {

	private ParcourtId id;
	private Etudiant etudiant;
	private Niveau niveau;
	private String anneeAcademique;
	private int conduite;
	private int moyenne;

	public Parcourt() {
	}

	public Parcourt(ParcourtId id, Etudiant etudiant, Niveau niveau, String anneeAcademique, int conduite,
			int moyenne) {
		this.id = id;
		this.etudiant = etudiant;
		this.niveau = niveau;
		this.anneeAcademique = anneeAcademique;
		this.conduite = conduite;
		this.moyenne = moyenne;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idEtudiant", column = @Column(name = "IdEtudiant", nullable = false)),
			@AttributeOverride(name = "idNiveau", column = @Column(name = "IdNiveau", nullable = false)) })
	public ParcourtId getId() {
		return this.id;
	}

	public void setId(ParcourtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdEtudiant", nullable = false, insertable = false, updatable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdNiveau", nullable = false, insertable = false, updatable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Column(name = "Annee_academique", nullable = false, length = 10)
	public String getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(String anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@Column(name = "conduite", nullable = false)
	public int getConduite() {
		return this.conduite;
	}

	public void setConduite(int conduite) {
		this.conduite = conduite;
	}

	@Column(name = "moyenne", nullable = false)
	public int getMoyenne() {
		return this.moyenne;
	}

	public void setMoyenne(int moyenne) {
		this.moyenne = moyenne;
	}

}
